default:
  image: docker-hub.repo.splunkdev.net/python:3.11

variables:
  EXTRACTO_VERSION:
    value: "1.0.60"
    description: "The version of extracto to use"
  SKIP_DOWNSTREAM_TESTING:
    value: "False"
    description: "If true, downstream testing will be suppressed (useful for debugging or forcing a release in an emergency)."
  ENABLE_INTEGRATION_TESTING:
    value: "True"
    description: "Flag indicating that integration testing should be performed. Defaults to True, may be suppressed in some workflows."

stages:
  - build
  - app_inspect
  - test
  - release

include:
  - local: "pipeline/.build.yml"
  - local: "pipeline/.app-inspect.yml"
  - local: "pipeline/.test.yml"
  - local: "pipeline/.release.yml"
  - local: "pipeline/.post.yml"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^release_v[0-9]+\.[0-9]+\.[0-9]+$/
