name: Linux At Application Execution
id: bf0a378e-5f3c-11ec-a6de-acde48001122
version: 2
date: '2022-05-26'
author: Teoderick Contreras, Splunk
status: production
type: Anomaly
description: The following analytic identifies a suspicious process creation of At
  application. This process can be used by malware, adversaries and red teamers to
  create persistence entry to the targeted or compromised host with their malicious
  code. This anomaly detection can be a good indicator to investigate the event before
  and after this process execution, when it was executed and what schedule task it
  will execute.
data_source:
- Sysmon Event ID 1
search:
  selection1:
    ParentImage:
    - at
    - atd
  selection2:
    Image|endswith:
    - at
    - atd
  condition: selection1 or selection2
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints into the Endpoint datamodel. If you are using Sysmon, you can use the
  Add-on for Linux Sysmon from Splunkbase.
known_false_positives: Administrator or network operator can use this application
  for automation purposes. Please update the filter macros to remove false positives.
references:
- https://attack.mitre.org/techniques/T1053/001/
- https://www.linkedin.com/pulse/getting-attacker-ip-address-from-malicious-linux-job-craig-rowland/
tags:
  analytic_story:
  - Linux Privilege Escalation
  - Linux Persistence Techniques
  - Linux Living Off The Land
  asset_type: Endpoint
  confidence: 30
  impact: 30
  message: At application was executed in $dest$
  mitre_attack_id:
  - T1053.002
  - T1053
  observable:
  - name: dest
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 9
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1053.002/at_execution/sysmon_linux.log
    source: Syslog:Linux-Sysmon/Operational
    sourcetype: sysmon:linux
