name: Linux At Allow Config File Creation
id: 977b3082-5f3d-11ec-b954-acde48001122
version: 1
date: '2021-12-17'
author: Teoderick Contreras, Splunk
status: production
type: Anomaly
description: The following analytic identifies a suspicious file creation of /etc/at.allow
  or /etc/at.deny. These 2 files are commonly abused by malware, adversaries or red
  teamers to persist on the targeted or compromised host. These config files can restrict
  or allow user to execute "at" application (another schedule task application in
  linux). attacker can create a user or add the compromised username to that config
  file to execute "at" to schedule it malicious code. This anomaly detection can be
  a good indicator to investigate further the entry in created config file and who
  created it to verify if it is a false positive.
data_source:
- Sysmon Event ID 11
search:
  selection1:
    TargetFilename:
    - '*/etc/at.allow'
    - '*/etc/at.deny'
  condition: selection1
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the file name, file path, and process_guid executions from your endpoints
  into the Endpoint datamodel. If you are using Sysmon, you can use the Add-on for
  Linux Sysmon from Splunkbase.
known_false_positives: Administrator or network operator can create this file for
  automation purposes. Please update the filter macros to remove false positives.
references:
- https://linuxize.com/post/at-command-in-linux/
tags:
  analytic_story:
  - Linux Privilege Escalation
  - Linux Persistence Techniques
  - Linux Living Off The Land
  asset_type: Endpoint
  confidence: 50
  impact: 50
  message: A file $file_name$ is created in $file_path$ on $dest$
  mitre_attack_id:
  - T1053.003
  - T1053
  observable:
  - name: dest
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 25
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1053.002/at_execution/sysmon_linux.log
    source: Syslog:Linux-Sysmon/Operational
    sourcetype: sysmon:linux
