include:
  - local: "pipeline/.install-contentctl.yml"
 
# This CI job validates and builds the ESCU/BA/API package
build:
  stage: build
  artifacts:
    when: always
    paths:
      - artifacts/*
    expire_in: 14 days
  before_script:
      - !reference [.install-contentctl, before_script]
  script:
    - echo "Validating and Building all files in the dist/ directory"
    - pip list
    - echo "ContentCTL build starting..."
    - contentctl build --enrichments 
    - echo "ContentCTL build finished"

  after_script:
    - mkdir -p artifacts
    - cp dist/DA-ESS-ContentUpdate-latest.tar.gz artifacts/
    - tar -czf artifacts/SSA-Content-latest.tar.gz -C dist/ssa .
    - tar -czf artifacts/SSE-API-latest.tar.gz -C dist/api .

