# init creds-helper
.creds-init:
  before_script: |
    eval $(creds-helper init)
  id_tokens:
    CI_JOB_JWT:
      aud: $CICD_VAULT_ADDR

# acquire reader role
.generic-read:
  before_script: |
    if [ "${CI_COMMIT_REF_PROTECTED}" == true ] ; then
        export GENERIC_READ_ROLE="artifactory:v2/cloud/role/generic-reader-threat-research-security-content-prod-role"
    else
        export GENERIC_READ_ROLE="artifactory:v2/cloud/role/generic-reader-threat-research-security-content-test-role"
    fi
    eval $(creds-helper artifactory --eval ${GENERIC_READ_ROLE})
